name: Generate Mavely Link
on:
  repository_dispatch:
    types: [generate_link]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests
      - name: Run Generator
        env:
          MAVELY_COOKIES: ${{ secrets.MAVELY_COOKIES }}
        run: python generator.py "${{ github.event.client_payload.url }}" "${{ github.event.client_payload.row_id }}"
